host:
  anbient: 'https://www.anbient.com'
  myAnimeList: 'https://myanimelist.net'
  punchsub: 'https://punchsub.zlx.com.br'


uris:
  anbient: ['/animes/', '/tv/', '/TV/', '/anime/', '/ova/']
  punchsub: ["/lista-de-animes", "/lista-de-ovas", "/lista-de-filmes"]


exclude: []
