host:
  anbient: 'https://www.anbient.com'
  myAnimeList: 'https://myanimelist.net'
  punchsub: 'https://punchsub.zlx.com.br'
  kitsu: 'https://kitsu.io/api/edge'


uris:
  anbient: ['/animes/', '/tv/', '/TV/', '/anime/', '/ova/']
  punchsub: ["/lista-de-animes"]


exclude: []
