host:
  anbient: 'https://www.anbient.com'
  punchsub: 'https://punchsub.zlx.com.br'
  myAnimeList: 'https://myanimelist.net'


uris:
  anbient: ['/animes/', '/tv/', '/TV/', '/anime/', '/ova/']
  punchsub:
    animes: "lista-de-animes"
    filmes: "lista-de-filmes"
    ovas: "lista-de-ovas"


exclude: []
